### PR TITLE
Replaced plain-text error messages to Bootstrap-like alerts

### PR DESCRIPTION
**Pull request by Raj-292**
For issue : Stylize Error Messages : #2 
Added "customAlert" class under App.css to show a bootstrap-like alert. Can add different shades like bootstrap if required in further commits.
image

### CODE REVIEW

**Comment by burntcarrot** [comment]
Thanks! Was looking for this. Can you also please provide a screenshot in mobile view via Inspect Tools?

**Comment by burntcarrot** [comment]
Can you see the comments I made above?

**Comment by burntcarrot** [comment]
Closed in favor of #4.

**Comment by Raj-292** [comment]
> Thanks! Was looking for this. Can you also please provide a screenshot in mobile view via Inspect Tools?
iphone X

**Comment by Raj-292** [comment]
@burntcarrot To be honest, the extra padding caused due to <p> tag doesn't look good and takes up extra space.

**Comment by burntcarrot** [comment]
I agree. But since you didn't mention that you wanted to take up this issue, I assigned it to someone else.

If you still want to make changes in a new PR, you can, but remember that the PR won't be counted for Hacktoberfest (minor changes don't count).

If you know how to use the React Testing library, feel free to take Issue 1, I'll be happy to merge your PR in that case!

**Comment by Raj-292** [comment]
Well, I was the one who added the css for Alerts. Nevermind.

**Pull request closed without merging**
